# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          rid: linux-x64
        - os: windows-latest
          rid: win-x64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/encrypt
    - name: Build
      run: dotnet build --no-restore ./src/encrypt
    - name: Test
      run: dotnet publish -r ${{ matrix.rid }} --self-contained ./src/encrypt
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: encrypt-cli
        path: |
          src/encrypt/bin/Release/net9.0/win-x64/publish/encrypt.exe
          src/encrypt/bin/Release/net9.0/win-x64/publish/encrypt
